project_id = "kfgfkmzbefbrvyanxayu"

[functions.process-file]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.hubspot-sync]
verify_jwt = true