// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfgfkmzbefbrvyanxayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZ2ZrbXpiZWZicnZ5YW54YXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDI5NzYsImV4cCI6MjA2OTM3ODk3Nn0.1EOnfI5G9FQE9d4DwTt90PbK0KbbFcpnx6uRrDplU4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});